[build]
  command = "npm run build"
  publish = "dist/"

[build.processing]
  skip_processing = false
  [css]
    bundle = false
    minify = false
  [js]
    bundle = false
    minify = false
  [html]
    pretty_urls = true
  [images]
    compress = true

[dev]
  autoLaunch = false
  command = "npm start"
  framework = "#custom"
  targetPort = 8888
