version: 2.1
aliases:
  - &defaults
    executor:
      name: node
    working_directory: /mnt/ramdisk
executors:
  node:
    description: Circle CI standard node docker image
    docker:
      - image: circleci/node:14
jobs:
  install:
    <<: *defaults
    description: Load and cache node modules, restoring from cache if available
    steps:
      - checkout
      - restore_cache:
          keys:
            - sauce-dependencies-{{ checksum "package-lock.json" }}
            - sauce-dependencies-
      - run:
          command: npm install
          name: Install Node dependencies
      - save_cache:
          paths:
            - ~/.npm
          key: sauce-dependencies-{{ checksum "package-lock.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  sass-unit-test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: npm run test:ci
          name: Run Sass unit tests
  chromatic-deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: npm run chromatic:deploy
          name: Chromatic - accept all changes
  chromatic-test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: npm run chromatic:test
          name: Chromatic - report changes to chromatic
workflows:
  version: 2.1
  tests:
    jobs:
      - install
      - sass-unit-test:
          requires:
            - install
      - chromatic-test:
          requires:
            - install
          filters:
            branches:
              ignore: main
      - chromatic-deploy:
          requires:
            - install
          filters:
            branches:
              only: main
