version: 2.1
commands:
  load-node-modules:
    description: Load and cache node modules, restoring from cache if available
    steps:
      - restore_cache:
          keys:
            - v2-npm-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          paths:
            - ~/.npm
          key: v2-npm-{{ checksum "package-lock.json" }}
  chromatic-test-accept-all-changes:
    description: Chromatic - accept all changes
    steps:
      - run: npm run chromatic test --auto-accept-changes
  chromatic-test-exit-cleanly-on-changes:
    description: Chromatic - report changes to chromatic
    steps:
      - run: npm run chromatic test --exit-zero-on-changes
  jest-test:
    description: Run unit tests
    steps:
      - run: npm run test-ci
executors:
  node:
    description: Circle CI standard node docker image
    docker:
      - image: circleci/node:12.18.2
jobs:
  test:
    executor:
      name: node
    steps:
      - checkout
      - load-node-modules
      - jest-test
  chromatic-run-and-accept-all:
    executor:
      name: node
    steps:
      - checkout
      - load-node-modules
      - chromatic-test-accept-all-changes
  chromatic-test:
    executor:
      name: node
    steps:
      - checkout
      - load-node-modules
      - chromatic-test-exit-cleanly-on-changes
workflows:
  version: 2.1
  tests:
    jobs:
      - test
      - chromatic-test:
          filters:
            branches:
              ignore: master
      - chromatic-run-and-accept-all:
          filters:
            branches:
              only: master
