version: 2.1
orbs:
  node: circleci/node@4.5.1
jobs:
  test:
    docker:
      - image: 'cimg/node:lts'
    steps:
      - checkout
      - node/install-packages
      - node/test:
          run-command: jest --runInBand
workflows:
  sass-mixin-tests:
    jobs:
      - test
