version: 2.1
aliases:
  - &defaults
    executor:
      name: node
    docker:
      - image: circleci/node:12-browsers
    working_directory: /tmp/storybook
executors:
  node:
    description: Circle CI standard node docker image
    docker:
      - image: circleci/node:12.18.2
jobs:
  install:
    <<: *defaults
    description: Load and cache node modules, restoring from cache if available
    steps:
      - checkout
      - restore_cache:
          keys:
            - sauce-packages-{{ checksum "package-lock.json" }}
      - run:
          command: npm ci
          name: Install Node dependencies
      - save_cache:
          paths:
            - ~/.npm
          key: sauce-packages-{{ checksum "package-lock.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  sass-unit-test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: npm run test-ci
          name: Run Sass unit tests
  chromatic-run-and-accept-all:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: npm run chromatic test --auto-accept-changes master
          name: Chromatic - accept all changes
  chromatic-test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: npm run chromatic test --exit-once-uploaded
          name: Chromatic - report changes to chromatic
workflows:
  version: 2.1
  tests:
    jobs:
      - install
      - sass-unit-test:
          requires:
            - install
      - chromatic-test:
          requires:
            - install
          filters:
            branches:
              ignore: master
      - chromatic-run-and-accept-all:
          requires:
            - install
          filters:
            branches:
              only: master
