version: 2
orbs:
  chromatic: wave/chromatic@1.3.0
jobs:
  test:
    docker:
      - image: circleci/node:12.18.2
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-npm-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          paths:
            - ~/.npm
          key: v2-npm-{{ checksum "package-lock.json" }}
      - run:
          name: Run unit tests
          command: npm run test-ci
workflows:
  main-workflow:
    jobs:
      - test
      - chromatic/test:
          filters:
            branches:
              ignore: master
      - chromatic/run-and-accept-all:
          filters:
            branches:
              only: master
