version: 2.1
orbs:
  node: circleci/node@4.5.1
jobs:
  test:
    docker:
      - image: 'cimg/node:14'
    steps:
      - checkout
      - node/install
      - run:
          command: npm run ci:test
workflows:
  sass-mixin-tests:
    jobs:
      - test
