version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12.18.2
    environment:
      - BASE_HREF: undefined
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-npm-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          paths:
            - ~/.npm
          key: v2-npm-{{ checksum "package-lock.json" }}
      - run:
          name: Run tests
          command: |
            npm run test-ci
