---
commands:
  chromatic-test-accept-all-changes:
    steps:
      - run:
          command: 'npm run chromatic test --auto-accept-changes'
          name: 'Chromatic - accept all changes'
  chromatic-test-exit-cleanly-on-changes:
    steps:
      - run:
          command: 'npm run chromatic test --exit-zero-on-changes'
          name: 'Chromatic - report changes to chromatic'
  jest-test:
    steps:
      - command: 'npm run test-ci'
        name: 'Run unit tests'
        run: ~
  load-node-modules:
    description: 'Load and cache node modules, restoring from cache if available'
    steps:
      - restore_cache:
          keys:
            - 'v2-npm-{{ checksum "package-lock.json" }}'
      - run: 'npm ci'
      - save_cache:
          key: 'v2-npm-{{ checksum "package-lock.json" }}'
          paths:
            - ~/.npm
jobs:
  chromatic-run-and-accept-all:
    steps:
      - checkout
      - load-node-modules
      - chromatic-test-accept-all-changes
  chromatic-test:
    steps:
      - checkout
      - load-node-modules
      - chromatic-test-exit-cleanly-on-changes
  test:
    docker:
      - image: 'circleci/node:12.18.2'
    steps:
      - checkout
      - load-node-modules
      - jest-test
    working_directory: ~/repo
version: 2.1
workflows:
  tests:
    jobs:
      - test
      - chromatic-test:
          filters:
            branches:
              ignore: master
      - chromatic-run-and-accept-all:
          filters:
            branches:
              only: master
  version: 2.1
