title: Type
status: ready
context:
  element: p
  content: Sauce Design System
  button:
    label: 'A Nested Button!'
variants:
  - name: 'Signpost Hero Heading'
    context:
      class: heading-signpost-hero
      element: h1
      content: Heading Signpost Hero
  - name: 'Hero Heading'
    context:
      class: heading-hero
      element: h1
      content: Heading Hero
  - name: 'Primary Heading'
    context:
      class: heading-primary
      element: h1
      content: Heading Primary
  - name: 'Secondary Heading'
    context:
      class: heading-secondary
      element: h2
      content: Heading Secondary
  - name: 'Tertiary Heading'
    context:
      class: heading-tertiary
      element: h3
      content: Heading Tertiary
  - name: 'Item Heading'
    context:
      class: heading-item
      element: h3
      content: Heading Item
